name: appwrite_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  appwrite: ^13.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  get_it: ^8.0.0
  go_router: ^14.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
